apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: war-db-volume
  name: war-db-volume
  namespace: war-ns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}