apiVersion: v1
kind: Service
metadata:
  name: war-frontend-svc
  namespace: war-ns
spec:
  type: ClusterIP
  selector:
    app: war-frontend-dp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
