apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: war-frontend-dp-hpa
  namespace: war-ns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: war-frontend-dp
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60