apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: war-backend-dp-hpa
  namespace: war-ns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: war-backend-dp
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 40